[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "pip3 install yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"